name: ingressinhos_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  brasil_fields: ^1.19.0
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.1.0
  get_it: ^9.2.1
  google_fonts: ^8.1.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
